on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
        with:
          clean: "false"
      - name: Build node.js
        shell: bash

        run: |
          npm install
          npm run build
          pm2 reload appendixservice
