on:
  workflow_dispatch:
  push:
    branches: [prod]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
        with:
          clean: "false"
          path: "prod"
      - name: Building and deploying app to production...
        shell: "bash -ieo pipefail {0}"
        run: |
          cd prod
          nvm install 18
          nvm use 18
          yarn install
          yarn run build
          pm2 reload prod-service
