type KillerWord = {
  sv: string;
  en: string;
};

export const KILLER_WORDS: KillerWord[] = [
  { sv: 'akademiker', en: 'academics' },
  { sv: 'alligator', en: 'alligator' },
  { sv: 'analfabet', en: 'illiterate' },
  { sv: 'ananas', en: 'pineapple' },
  { sv: 'arbetsplats', en: 'workplace' },
  { sv: 'askkopp', en: 'ashtray' },
  { sv: 'badboll', en: 'beach ball' },
  { sv: 'badrumsgolv', en: 'bathroom floor' },
  { sv: 'bagare', en: 'baker' },
  { sv: 'bakelse', en: 'pastry' },
  { sv: 'bibliotek', en: 'library' },
  { sv: 'bieffekt', en: 'side effect' },
  { sv: 'bokhylla', en: 'bookshelf' },
  { sv: 'brevbärare', en: 'postman' },
  { sv: 'brevlåda', en: 'mailbox' },
  { sv: 'brottsling', en: 'criminal' },
  { sv: 'brottsplats', en: 'crime scene' },
  { sv: 'bältdjur', en: 'armadillo' },
  { sv: 'cigarett', en: 'cigarette' },
  { sv: 'clown', en: 'clown' },
  { sv: 'dagisbarn', en: 'children' },
  { sv: 'dammsugare', en: 'vacuum cleaner' },
  { sv: 'diarré', en: 'diarrhea' },
  { sv: 'dinosaurie', en: 'dinosaur' },
  { sv: 'dromedar', en: 'dromedary' },
  { sv: 'duschdraperi', en: 'shower curtain' },
  { sv: 'elefant', en: 'elephant' },
  { sv: 'fax', en: 'fax' },
  { sv: 'fotboll', en: 'football' },
  { sv: 'frimärke', en: 'stamp' },
  { sv: 'frisör', en: 'hairdresser' },
  { sv: 'fyrverkeri', en: 'fireworks' },
  { sv: 'fågelholk', en: 'birdhouse' },
  { sv: 'fågelskrämma', en: 'scarecrow' },
  { sv: 'försäkring', en: 'insurance' },
  { sv: 'gaffatejp', en: 'duct tape' },
  { sv: 'guacamole', en: 'guacamole' },
  { sv: 'halsband', en: 'necklace' },
  { sv: 'hammare', en: 'hammer' },
  { sv: 'hårdrock', en: 'hard rock' },
  { sv: 'häftstift', en: 'thumbtack' },
  { sv: 'hästsvans', en: 'ponytail' },
  { sv: 'hörselskydd', en: 'ear protection' },
  { sv: 'italienare', en: 'Italian' },
  { sv: 'journalist', en: 'journalist' },
  { sv: 'kaffekvarn', en: 'coffee grinder' },
  { sv: 'kapitel', en: 'chapter' },
  { sv: 'killergame', en: 'killer game' },
  { sv: 'kjol', en: 'skirt' },
  { sv: 'kofot', en: 'crowbar' },
  { sv: 'kokbok', en: 'cookbook' },
  { sv: 'kollega', en: 'colleague' },
  { sv: 'krokodil', en: 'crocodile' },
  { sv: 'kupong', en: 'coupon' },
  { sv: 'kurragömma', en: 'hide and seek' },
  { sv: 'kvadratmeter', en: 'square meter' },
  { sv: 'källare', en: 'basement' },
  { sv: 'känguru', en: 'kangaroo' },
  { sv: 'lejon', en: 'lion' },
  { sv: 'madrass', en: 'mattress' },
  { sv: 'margarin', en: 'margarine' },
  { sv: 'missförstånd', en: 'misunderstanding' },
  { sv: 'misstag', en: 'mistake' },
  { sv: 'morgonrock', en: 'housecoat' },
  { sv: 'noshörning', en: 'rhinoceros' },
  { sv: 'nätverk', en: 'network' },
  { sv: 'ordbank', en: 'vocabulary' },
  { sv: 'pennvässare', en: 'pencil sharpener' },
  { sv: 'påskhare', en: 'easter bunny' },
  { sv: 'räkning', en: 'bill' },
  { sv: 'saltkar', en: 'salt shaker' },
  { sv: 'schampo', en: 'shampoo' },
  { sv: 'shoppingcenter', en: 'shopping center' },
  { sv: 'silvertejp', en: 'duct tape' },
  { sv: 'sjukhus', en: 'hospital' },
  { sv: 'sjuksköterska', en: 'nurse' },
  { sv: 'skolbänk', en: 'school desk' },
  { sv: 'skruvmejsel', en: 'screwdriver' },
  { sv: 'skräckfilm', en: 'horror movie' },
  { sv: 'skådespelare', en: 'actor' },
  { sv: 'snowboard', en: 'snowboard' },
  { sv: 'spiraltrappa', en: 'spiral staircase' },
  { sv: 'stadsbuss', en: 'city ​​bus' },
  { sv: 'strykbräde', en: 'ironing board' },
  { sv: 'taklampa', en: 'ceiling lamp' },
  { sv: 'tandborste', en: 'toothbrush' },
  { sv: 'tandkräm', en: 'toothpaste' },
  { sv: 'tandläkare', en: 'dentist' },
  { sv: 'tandpetare', en: 'toothpick' },
  { sv: 'tandställning', en: 'braces' },
  { sv: 'tandtråd', en: 'dental floss' },
  { sv: 'telefonsvarare', en: 'answering machine' },
  { sv: 'termometer', en: 'thermometer' },
  { sv: 'tiger', en: 'tiger' },
  { sv: 'toalettpapper', en: 'toilet paper' },
  { sv: 'torkskåp', en: 'drying cabinet' },
  { sv: 'torktumlare', en: 'dryer' },
  { sv: 'tsatsiki', en: 'tzatziki' },
  { sv: 'tuggummi', en: 'chewing gum' },
  { sv: 'tunnelbana', en: 'subway' },
  { sv: 'turist', en: 'tourist' },
  { sv: 'tvättstuga', en: 'laundry' },
  { sv: 'tvättställ', en: 'sink' },
  { sv: 'tågstation', en: 'train station' },
  { sv: 'tändsticka', en: 'match' },
  { sv: 'vardagsrum', en: 'living room' },
  { sv: 'varm choklad', en: 'hot chocolate' },
  { sv: 'vattenfall', en: 'waterfall' },
  { sv: 'vattenkokare', en: 'kettle' },
  { sv: 'vattenmelon', en: 'watermelon' },
  { sv: 'vattenpistol', en: 'water gun' },
  { sv: 'vårdcentral', en: 'health center' },
  { sv: 'vårdnadshavare', en: 'caregiver' },
  { sv: 'återvinning', en: 'recycling' },
  { sv: 'öken', en: 'desert' },
  { sv: 'önskelista', en: 'wish list' },
  { sv: 'örngott', en: 'pillowcase' },
].sort((a, b) => a.sv.localeCompare(b.sv, 'sv-SE'));
